### ISSUE TITLE
Send to BTC Address: Unexpected error screen

### ISSUE THREAD

**Issue by ok300** [breez/c-breez#795] opened 2024-02-21 10:06 UTC
Steps I took:
- start c-breez
- go to Send to BTC Address screen
  - it showed "transport error, please try agian later"
  - go back to main screen
- go to Send to BTC Address screen again
  - it showed the following error

![Screenshot from 2024-02-21 11-03-19](https://github.com/breez/c-breez/assets/106775972/8b350618-5f81-445e-86c0-115d83815630)

**Comment by dangeross** [comment] 2024-03-21 08:37
Seems flaky. Sometimes works, sometimes not. Testing this I also get several different errors, all relating to `onchain_payment_limits`:

```
[WithdrawFundsAvailableBtc] {INFO} (2024-03-21T08:30:34.437018Z) : Building with wallet balance: 24701 balance: 20766 maxSendableAmount: 0
[RevSwapsInProgressBloc] {INFO} (2024-03-21T08:30:38.316076Z) : reverse swaps in progress polling finished
[UserApp] {INFO} (2024-03-21T08:30:39.779442Z) : New inner route: /reverse_swap
[ReverseSwapBloc] {SEVERE} (2024-03-21T08:30:40.610255Z) : fetchOnchainPaymentLimits error
FrbAnyhowException(Service connectivity: (Boltz https://api.boltz.exchange/routinghints) Failed to parse get route hints response: expected value at line 1 column 1)
[Exceptions] {INFO} (2024-03-21T08:30:40.613633Z) : extractExceptionMessage: FrbAnyhowException(Service connectivity: (Boltz https://api.boltz.exchange/routinghints) Failed to parse get route hints response: expected value at line 1 column 1)
[Exceptions] {INFO} (2024-03-21T08:30:40.613755Z) : extractInnerErrorMessage: FrbAnyhowException(Service connectivity: (Boltz https://api.boltz.exchange/routinghints) Failed to parse get route hints response: expected value at line 1 column 1)
```

```
[WithdrawFundsAvailableBtc] {INFO} (2024-03-21T08:31:16.560211Z) : Building with wallet balance: 24701 balance: 20766 maxSendableAmount: 0
[RevSwapsInProgressBloc] {INFO} (2024-03-21T08:31:20.824853Z) : reverse swaps in progress polling finished
[UserApp] {INFO} (2024-03-21T08:31:22.396064Z) : New inner route: /reverse_swap
[ReverseSwapBloc] {SEVERE} (2024-03-21T08:31:22.741993Z) : fetchOnchainPaymentLimits error
FrbAnyhowException(Generic: Generic: expected value at line 1 column 1)
[Exceptions] {INFO} (2024-03-21T08:31:22.749126Z) : extractExceptionMessage: FrbAnyhowException(Generic: Generic: expected value at line 1 column 1)
[Exceptions] {INFO} (2024-03-21T08:31:22.749401Z) : extractInnerErrorMessage: FrbAnyhowException(Generic: Generic: expected value at line 1 column 1)
```

**Comment by ok300** [comment] 2024-03-21 09:01
> FrbAnyhowException(Service connectivity: (Boltz https://api.boltz.exchange/routinghints) Failed to parse get route hints response: expected value at line 1 column 1)

Looks like the call to the Boltz routing hints fails.

Even calling it with a bogus `routingNode` arg still returns a valid response

```bash
curl -X POST -H "Content-Type: application/json" -d '{"routingNode":"abc",  "symbol": "BTC"}' https://api.boltz.exchange/routinghints

# {"routingHints":[]}
```

The error

```
FrbAnyhowException(Generic: Generic: expected value at line 1 column 1)
```
means we tried to parse a JSON response, but we received non-JSON.

So then I suspect it's a general connectivity problem.

**Comment by ok300** [comment] 2024-03-21 09:03
Separate from the error, I think the screen shouldn't show a big red box.

A more user-friendly "Something went wrong, please try again later" for example.

**Comment by dangeross** [comment] 2024-03-21 09:07
In my case I never got the big red box, I couldn't reproduce that

**Comment by roeierez** [comment] 2024-03-25 09:15
> Separate from the error, I think the screen shouldn't show a big red box.
> 
> A more user-friendly "Something went wrong, please try again later" for example.

The red error indicates a debug build that had some errors in rendering. This representation will not be shown in production.

**Comment by erdemyerebasmaz** [comment] 2024-04-13 14:42
I believe this is fixed with changes to polling logic on reverse swap / swap in progress bloc's.

Mocked network errors but was unable to reproduce, closing.

**Closed by erdemyerebasmaz** 2024-04-13 14:42 UTC
