### ISSUE TITLE
Select LSP warning is shown after restore although node is connected to default LSP

### ISSUE THREAD

**Issue by erdemyerebasmaz** [breez/c-breez#520] opened 2023-03-06 12:22 UTC

**Comment by ubbabeck** [comment] 2023-06-21 12:16
Have not been able to reproduce this issue on the iOS TestFlight version nor when building the android on my emulator. 

On the other hand if I build the the app without the _config.json_ file added we run into this error, but I guess that this is a feature and not a bug. 

I believe we can close this issue. What do you think @roeierez?

**Closed** 2023-06-22 07:56 UTC
Labels: bug
