### ISSUE TITLE
LNURL withdraw is failing for `opentip.io`

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#578] opened 2023-06-16 09:06 UTC
I have sent tips to opentip.io (http://opentip.io/) LNURL-pay QR code
1. The payment is sent but it does not appear on the payment screen until I make another payment then both of them show up or reopen CBreez
2. The second time when I sent to opentip.io (http://opentip.io/) LNURL-pay this message was displayed (the payment went through)
3. In the logs (the last 2 payments are for the examples above)

![image](https://github.com/breez/c-breez/assets/127208515/0f9b06a0-8724-4536-b5ca-d2df5a56d9d1)
[c-breez.logs (1).zip](https://github.com/breez/c-breez/files/11768345/c-breez.logs.1.zip)

**Comment by Nackoo2000** [comment] 2023-06-30 14:32
Just tested again LNURL from Android.
LNURL - Pay to Opentip.io failed
LNURL - Withdraw from Opentip.io failed.

**Comment by erdemyerebasmaz** [comment] 2023-07-07 15:43
LNURL payments do succeed during my tests. 

> 1. The payment is sent but it does not appear on the payment screen until I make another payment then both of them show up or reopen CBreez

Can't reproduce this, payments do show up immediately after succeeding.

However, withdrawing tips fail. Logs attached:

[opentip.io withdraw.txt](https://github.com/breez/c-breez/files/11983755/opentip.io.withdraw.txt)

Changing title of the issue.

**Comment by ubbabeck** [comment] 2023-07-07 19:16
I managed to do a LNURLW earlier today before they started to fail. I think we can close this issue.
![signal-2023-07-07-211604](https://github.com/breez/c-breez/assets/36157890/522335ac-3035-410d-89f5-b3bc7b5aa721)

**Closed** 2023-07-08 10:33 UTC
