### ISSUE TITLE
Payment to destination not working

### ISSUE THREAD

**Issue by Nackoo2000** [breez/c-breez#572] opened 2023-06-14 10:18 UTC
Tested on Opentip.io

**Comment by kingonly** [comment] 2023-06-14 10:23
Does it work in Breez mobile? What's not working? Did you test other urls like Wallet of Satoshi?

**Comment by Nackoo2000** [comment] 2023-06-14 10:41
It is working on mobile. I can't send via LNURL-pay to WoS also.

![image](https://github.com/breez/c-breez/assets/127208515/2f97d085-f9b3-4872-8520-d4c5fc9e7780)
[c-breez.logs (3).zip](https://github.com/breez/c-breez/files/11744748/c-breez.logs.3.zip)

**Comment by kingonly** [comment] 2023-06-14 11:12
This issue seems unrelated to lnurl. You can't send to the destination. Please work with Roei to report these issues to Greenlight ASAP.

**Comment by kingonly** [comment] 2023-06-16 06:58
This isn't lnurl related, so change the subject

**Comment by roeierez** [comment] 2023-07-13 06:30
@Nackoo2000 is this still not working on the latest build after the fee settings fix?

**Comment by Nackoo2000** [comment] 2023-07-13 06:51
On WoS everything works.
I can send to opentip via LNURL-pay but **can't do LNURL-Witdraw with CBreez.**
The LNURL - withdraw works with Breez mobile AND I tested LNURL-withdraw from Fountain with CBreez it works.


[c-breez.logs (13).zip](https://github.com/breez/c-breez/files/12036231/c-breez.logs.13.zip)
![image](https://github.com/breez/c-breez/assets/127208515/a75d77bb-aafb-4b47-9b2d-657ed45d93f2)

**Comment by ubbabeck** [comment] 2023-07-17 12:38
I have contacted opentip regarding this issue since it is from them we are receiving the unknown error. Awaiting their answer.

**Comment by ubbabeck** [comment] 2023-07-18 09:40
After speaking with opentip.io we confirmed that the issue is not with how we handle lnurl. The issue is on their side, will  keep this open as we are waiting for their resolution.

**Comment by roeierez** [comment] 2023-09-18 07:37
@ubbabeck any update on this?

**Comment by ubbabeck** [comment] 2023-09-18 08:26
> @ubbabeck any update on this?

lnurlp to opentip.io works ✅ 

lnurlw fails with the same error `Unexpected error` ❌

**Comment by kingonly** [comment] 2023-09-18 11:08
@ubbabeck if it happens on Breez mobile, we should close the issue.

**Comment by ubbabeck** [comment] 2023-09-18 11:47
@kingonly Forgot to add that context, lnurlw from opentip.io works in Breez mobile, but not in c-breez.

**Comment by kingonly** [comment] 2023-09-18 11:56
> @kingonly Forgot to add that context, lnurlw from opentip.io works in Breez mobile, but not in c-breez.

What's causing this? What is the difference?
If that's correct, why are we waiting for opentip to fix something?

**Comment by ubbabeck** [comment] 2023-09-18 12:28
> > @kingonly Forgot to add that context, lnurlw from opentip.io works in Breez mobile, but not in c-breez.
> 
> What's causing this? What is the difference? If that's correct, why are we waiting for opentip to fix something?

We are yet not sure what is causing this issue and in theory there should not be any difference. 

When in dialog with them, in July, a lnurlw invoice failed due to `no_route`, though this was an ongoing issue at the time for payments using the SDK. They also told me that they had issue with their liquidity and that they would handle this. 

@ok300 and me will work together in order to figure out the root cause of the issue.

**Comment by ubbabeck** [comment] 2023-10-11 09:55
- 100 sats lnurlp and lnurlw ✅ 
- 1000 sats lnurlp and lnurlw ✅ 
- 10000 sats lnurlp  ❌

**Comment by kingonly** [comment] 2023-10-11 10:41
@ubbabeck it means it's a liquidity or a gossip issue, not related to to lnurlp. We should test against WoS and in any case, close this issue.

**Comment by ubbabeck** [comment] 2023-10-11 10:54
Okay, that was my theory too, thanks. 

Closing the issue.

**Closed by ubbabeck** 2023-10-11 10:54 UTC
Labels: bug
