### ISSUE TITLE
Lightning address doesn't work 

### ISSUE THREAD

**Issue by kingonly** [breez/c-breez#497] opened 2023-02-21 04:40 UTC

**Comment by erdemyerebasmaz** [comment] 2023-02-22 13:11
LNURL's from https://lightsats.com/signin no longer work either. They did work when we were testing deep links(~3 weeks ago).

Example address:

> lnurl1dp68gurn8ghj7mrfva58gumpw3ejucm0d5hkzurf9ash2arg9akxuatjdshkgmedd3hkw6tw8a4nz0fnvcunzerzv33nzv33xq6nydp3893xyveexdnxxdtpx93rydfjvsmx2e3cx5cnyvny8ymr2etxvcunse34vcmrycfnvs6r2dtrxyuk2fn5v9nn6mr0va5kuvsme0w

We're still using dart_lnurl plugin to parse so don't bother checking SDK.

**Comment by roeierez** [comment] 2023-02-22 13:45
Let's also remove the dart_lnurl as part of this fix.

**Comment by erdemyerebasmaz** [comment] 2023-02-22 14:13
> Let's also remove the dart_lnurl as part of this fix.

There are still missing parts from the SDK, I've opened the ones I noticed. 
- https://github.com/breez/breez-sdk/issues/117 
- https://github.com/breez/breez-sdk/issues/118

Even if everything is ready, it's a long task to replace dart_lnurl logic from LNURL payment & withdraw widgets, InputHandler, InputState etc. 
I suggest we keep this restricted to lightning address & the lnurl in question for now. 
We can discuss later if dart_lnurl is the reason for this issue & using SDK will address it w/o removal of existing features.

**Comment by kingonly** [comment] 2023-02-22 17:12
@erdemyerebasmaz the question isn't if dart_lnurl is good or bad. Breez Cloud is a reference app for the Breez SDK. The Breez SDK includes lnurl functionality and Breez Cloud need to showcase how to implement lnurl using the Breez SDK only.

**Comment by ademar111190** [comment] 2023-02-22 20:11
Hey guys, sorry for the long time to give updates; my internet stopped working suddenly today.

I did start the task by writing some unit tests, as you see on this draft https://github.com/breez/c-breez/pull/507

I concluded the problem is not on c-breez, so the bug is on the input parser.

As the idea is to remove the dart_lnurl, I'll move to the SDK to continue working on the issue and use this draft PR I shared above to integrate the changes.

P.S. We should start writing more unit tests more frequently and try to convert each bug report into a unit test to avoid regressions; if we had already done it, we would have noticed the lnurl stop working earlier.

**Comment by kingonly** [comment] 2023-02-22 20:19
@ademar111190 definitely re the unit tests!

**Comment by ademar111190** [comment] 2023-02-23 11:59
One more update, @erdemyerebasmaz asked to work on this issue, so I did push what I've done so far on these branches https://github.com/breez/breez-sdk/pull/121 and https://github.com/breez/c-breez/pull/507 

Summarizing what I've done so far:

- I created unit tests on input bloc and did confirm the bug was not there; our problem is in the parser https://github.com/breez/c-breez/pull/507/commits/896c0171ec97b6541028c599573a9f6f10514983
- I did remove Input Parser and dart_lnurl from the c-breez https://github.com/breez/breez-sdk/pull/121/commits/f0cebb103a8c8fde294caff5be34829ddead50d6
- I did create an integration test on c-breez to test the `parseInput` (not possible to unit test as the breez SDK doesn't support macOS/Linux yet, so through integration tests, I'm running the tests on an Android device) https://github.com/breez/c-breez/pull/507/commits/cbbd3b74c03940df4c3e2953080ddba339e4adee
- I did move part of the c-breez logic to use `parseInput` stopped here to give the task to Erdem. https://github.com/breez/c-breez/pull/507/commits/e7e3debb6ee1a57d0df831891e35d5b0f63a65f0

**Comment by roeierez** [comment] 2023-02-23 13:02
> The SDK core yes; the SDK flutter not yet. The test I'm mentioning is running against the BreezBridge which is part of the SDK flutter.

Right.

**Comment by roeierez** [comment] 2023-03-05 09:31
@erdemyerebasmaz what is the status of this?

**Comment by erdemyerebasmaz** [comment] 2023-03-06 09:51
@roeierez The payments are now being handled but the ln address information needs to be added to Payment Details Dialog.

**Comment by roeierez** [comment] 2023-03-06 09:54
I see. @ok300 added this ability to the sdk so should be easy I guess?

**Comment by erdemyerebasmaz** [comment] 2023-03-06 09:58
> I see. @ok300 added this ability to the sdk so should be easy I guess?

Yes, we only need to add it's widget. I'll close this issue after our meeting.

**Comment by erdemyerebasmaz** [comment] 2023-03-07 09:11
Lightning addresses are working through QR scan too however, there's an issue with most QR code generators tools online.
These QR codes have the same value but one has new line at the end and the other does not.
![frame-2](https://user-images.githubusercontent.com/4012752/223374241-33723908-4c82-4459-8fb0-170fa090d5c3.png)
```
Scanned string: 'erdem100@ln.tips
'
```
![frame](https://user-images.githubusercontent.com/4012752/223374173-b8ecd100-6df0-4af8-b0a7-3e2fd98dda36.png)
`Scanned string: 'http://erdem100@ln.tips')`

Keep this in mind when testing with online tools.

**Comment by roeierez** [comment] 2023-03-07 09:58
@ok300 I think the input parser should trim the given input before attempting to parse it (remove any variant of space from the edges).

**Comment by erdemyerebasmaz** [comment] 2023-03-07 10:15
> @ok300 I think the input parser should trim the given input before attempting to parse it (remove any variant of space from the edges).

@ok300 @roeierez If i wasn't clear the issue is with one of the most common [QR generator tool](https://www.qr-code-generator.com) online. It treats ln address as an url even though plain text format is selected.

Trimmed or not, it doesn't matter in this case. We would need to check if the url has an ln address but this really is an isolated case.

**Comment by erdemyerebasmaz** [comment] 2023-03-07 10:30
Ln address works as expected from clipboard & qr scan. Ln address information will be added to payment details dialog under another issues scope.
Closing.

**Closed by erdemyerebasmaz** 2023-03-07 10:30 UTC
